language: generic
sudo: false
git:
  depth: 10

matrix:
  include:
    - os: linux
      env: VIM_VERSION=v7.4
    - os: linux
      env: VIM_VERSION=v8.0.0000
    - os: linux
      env: VIM_VERSION=master
    - os: osx

addons:
  apt:
    packages:
      - language-pack-ja
      - vim
      - libperl-dev
      - python-dev
      - python3-dev
      - liblua5.1-0-dev
      - lua5.1

install:
  - bash scripts/install-vim.sh
  - export PATH=$HOME/vim/bin:$PATH

before_script:
  - curl -fsSL https://github.com/thinca/vim-themis/archive/v1.5.2.1.tar.gz | tar -xz -C /tmp
  - curl -fsSL https://github.com/Shougo/vimproc.vim/archive/master.tar.gz | tar -xz -C /tmp
  - make -C /tmp/vimproc.vim-master

script:
  - uname -a
  - which -a vim
  - vim --cmd version --cmd quit
  - vim --cmd "try | helptags doc/ | catch | cquit | endtry" --cmd quit
  # - /tmp/vim-themis-1.5.2.1/bin/themis --runtimepath /tmp/vimproc.vim-master --reporter dot
  - /tmp/vim-themis-1.5.2.1/bin/themis --runtimepath /tmp/vimproc.vim-master --exclude ConcurrentProcess --reporter dot
  - ruby scripts/check-changelog.rb
notifications:
  webhooks:
    urls:
      - http://travis-ci.herokuapp.com/vim
    on_success: never
    on_failure: always
    on_start: never
