version: '{build}'
clone_depth: 10
environment:
  matrix:
    - VIM_URL: http://vim-jp.org/redirects/koron/vim-kaoriya/vim74/oldest/win64/
    - VIM_URL: http://vim-jp.org/redirects/koron/vim-kaoriya/vim80/oldest/win64/
    - VIM_URL: http://vim-jp.org/redirects/koron/vim-kaoriya/latest/win64/
    # To test with latest official Vim binary, uncomment below line.
    #- VIM_URL: http://vim-jp.org/redirects/vim/vim-win32-installer/latest/x64/
install:
  - ps: |
      $zip = $Env:APPVEYOR_BUILD_FOLDER + '\vim.zip'
      $vim = $Env:APPVEYOR_BUILD_FOLDER + '\vim\'
      $redirect = Invoke-WebRequest -URI $Env:VIM_URL
      (New-Object Net.WebClient).DownloadFile($redirect.Links[0].href, $zip)
      [Reflection.Assembly]::LoadWithPartialName('System.IO.Compression.FileSystem') > $null
      [System.IO.Compression.ZipFile]::ExtractToDirectory($zip, $vim)
      $Env:THEMIS_VIM = $vim + (Get-ChildItem $vim).Name + '\vim.exe'
  - 'pushd %TEMP% && curl -fsSL https://github.com/Shougo/vimproc.vim/archive/ver.9.2.tar.gz | tar -xz && popd'
  - 'appveyor DownloadFile https://github.com/Shougo/vimproc.vim/releases/download/ver.9.2/vimproc_win64.dll -FileName %TEMP%\vimproc.vim-ver.9.2\lib\vimproc_win64.dll'

  - 'pushd %TEMP% && curl -fsSL https://github.com/thinca/vim-themis/archive/v1.5.2.1.tar.gz | tar -xz && popd'
  - 'reg copy HKLM\SOFTWARE\Python\PythonCore\2.7 HKLM\SOFTWARE\Python\PythonCore\2.7-32 /s /reg:32'
  - 'reg copy HKLM\SOFTWARE\Python\PythonCore\2.7 HKLM\SOFTWARE\Python\PythonCore\2.7-32 /s /reg:64'
build: off
test_script:
  - '%THEMIS_VIM% --version'
  - '%TEMP%\vim-themis-1.5.2.1\bin\themis.bat --runtimepath %TEMP%\vimproc.vim-ver.9.2 --exclude ConcurrentProcess --reporter dot'
deploy: off
notifications:
  - provider: Webhook
    url: http://appveyor.herokuapp.com/vim
    headers:
      User-Agent: appveyor-lingrbot 1.0
      Authorization:
        secure: cjzTMN7bP3fkRnz6S0ZRjc0Q3nPPvdJ7AXrizCQBKK0=
    on_build_success: false
    on_build_failure: true
